crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name="home"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register"),
    path('customer/<int:pk>', views.customer_page, name="customer"),
    path('customer_delete/<int:pk>', views.delete_customer, name="delete"),
    path('customer_add/', views.add_customer, name="add"),
    path('customer_update/<int:pk>', views.update_customer, name="update"),
]

website/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=10)
    zipcode = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

website/forms.py
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User
from django import forms
from . import models

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    first_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	

class AddCustomerForm(forms.ModelForm):
    first_name = forms.CharField(label="", max_length=50, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "First Name", "class": "form-control"}))
    last_name = forms.CharField(label="", max_length=50, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Last Name", "class": "form-control"}))
    email = forms.EmailField(label="", required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Email Address", "class": "form-control"}))
    phone = forms.CharField(label="", max_length=10, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Phone Number", "class": "form-control"}))
    address = forms.CharField(label="", max_length=50, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Address", "class": "form-control"}))
    state = forms.CharField(label="", max_length=10, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "State", "class": "form-control"}))
    city = forms.CharField(label="", max_length=50, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "City", "class": "form-control"}))
    zipcode = forms.CharField(label="", max_length=10, required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Zipcode", "class": "form-control"}))

    class Meta:
        model = models.Customer
        exclude = ("user",)

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import *
from . import models
import os
import random

# Create your views here.
def home(request):
    # Check if user is logging in
    customers = models.Customer.objects.all()

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        # Authenticate user
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You have successfully logged in!')
            return redirect('website:home')
        else:
            messages.success(request, 'There was an error logging in... Please Try again!')
            return redirect('website:home')
    else:
        return render(request, 'website/home.html', {
            "customers": customers
        })

def logout_user(request):
    logout(request)
    messages.success(request, 'You have been logged out.')
    return redirect('website:home')

def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate user
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, 'You have successfully registered! Welcome to CRM')
            return redirect('website:home')
    else:
        form = SignUpForm()

    return render(request, 'website/register.html',  {
        "form": form
    })

def customer_page(request, pk):
    # Show User record if logged in\
    image_list = os.listdir('./website/static/website')
    image = f"website/{random.choice(image_list)}"

    if request.user.is_authenticated:
        customer = models.Customer.objects.get(id=pk)
        return render(request, 'website/customer.html', {
            "customer": customer,
            "image": image
        })
    else:
        messages.success(request, "You must be logged in to view this page... Sorry!")
        return redirect('website:home')
    
def delete_customer(request, pk):
    if request.user.is_authenticated:
        customer = models.Customer.objects.get(id=pk)
        customer.delete()
        messages.success(request, "Customer Deleted Successfully...")
        return redirect('website:home')
    else:
        messages.success(request, "You must be logged in to do this action!")
        return redirect('website:home')

def add_customer(request):
    if request.user.is_authenticated:
        form = AddCustomerForm(request.POST or None)
        if request.method == "POST":
            if form.is_valid():
                add_record = form.save()
                messages.success(request, 'You have successfully added a new customer!')
                return redirect('website:home')
        return render(request, 'website/add_customer.html', {
            "form": form
        })
    else:
        messages.success(request, "You must be logged in to do this action!")
        return redirect('website:home')

def update_customer(request, pk):
    if request.user.is_authenticated:
        user = models.Customer.objects.get(id=pk)
        form = AddCustomerForm(request.POST or None, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully updated the customer!')
            return redirect('website:home')
        return render(request, 'website/update_customer.html', {
            "form": form,
            "customer": user
        })
    else:
        messages.success(request, "You must be logged in to do this action!")
        return redirect('website:home')

website/templates/website/add_customer.html
{% extends "website/base.html" %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>Add Customer</h1>
        <br>
        <form action="{% url 'website:add' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'website:home' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
{% endblock content %}

website/templates/website/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  <body>
    {% include "website/navbar.html" %}
    <div class="container">
        <br>
        {% if messages %}
          {% for message in messages  %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
  </body>
</html>

website/templates/website/customer.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
    <div class="card text-center mx-auto border border-3 border-secondary" style="width: 25rem;">
        <img src="{% static image %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{customer.first_name}} {{customer.last_name}}</h5>
        </div>
        <ul class="list-group list-group-flush mg-1">
            <li class="list-group-item">Phone: {{customer.phone}}</li>
            <li class="list-group-item">Email: {{customer.email}}</li>
            <li class="list-group-item">Address: {{customer.address}}</li>
            <li class="list-group-item">City: {{customer.city|title}}</li>
            <li class="list-group-item">State: {{customer.state|title}}</li>
            <li class="list-group-item">ZipCode: {{customer.zipcode}}</li>
        </ul>
        <div class="card-body">
        <a href="{% url 'website:update' customer.id %}" class="btn btn-dark">Edit</a>
        <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-modal">Delete</a>
        <a href="{% url 'website:home' %}" class="btn btn-secondary">Back</a>
        </div>
    </div>
  
    <!-- Modal -->
    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Warning</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <strong>Are you sure you want to delete this Record?</strong>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'website:delete' customer.id %}" type="button" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

website/templates/website/home.html
{% extends "website/base.html" %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Customers</h1>
        <table class="table table-bordered table-striped table-hover">
            <thead class="table-dark">
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Zipcode</th>
                <th scope="col">Created At</th>
                </tr>
            </thead>
            <tbody>
                {% if customers %}
                    {% for customer in customers %}
                        <tr> 
                            <td><a href="{% url 'website:customer' customer.id %}">{{customer.id}}</a></td>
                            <td>{{customer.first_name}} {{customer.last_name}}</td>
                            <td>{{customer.email}}</td>
                            <td>{{customer.phone}}</td>
                            <td>{{customer.address}}</td>
                            <td>{{customer.city}}</td>
                            <td>{{customer.state}}</td>
                            <td>{{customer.zipcode}}</td>
                            <td>{{customer.created_at}}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
            </table>
    {% else %}
        <div class="col-md-6 offset-md-3">
            <h1>Login</h1>
            <br>
            <form action="{% url 'website:home' %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Username" required>
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-secondary">Login</button>
            </form>
        </div>
    {% endif %}
{% endblock content %}

website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'website:home' %}">CRM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:add' %}">Add Customer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:home' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:register' %}">Register</a>
            </li>
          {% endif %}   
        </ul>
      </div>
    </div>
  </nav>

website/templates/website/register.html
{% extends "website/base.html" %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>Register</h1>
        <br>
        <form action="{% url 'website:register' %}" method="POST">
            {% csrf_token %}

            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Your Form Has Errors
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
		    {% endif %}

            {{form.as_p}}
            <br>
            <button type="submit" class="btn btn-secondary">Register</button>
        </form>
    </div>
{% endblock content %}

website/templates/website/update_customer.html
{% extends "website/base.html" %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>Edit Customer</h1>
        <br>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'website:customer' customer.id %}" class="btn btn-secondary">Back</a>
            <button type="submit" class="btn btn-dark">Update</button>
        </form>
    </div>
{% endblock content %}